<a href="https://colab.research.google.com/github/hjoddi/REI201G-python-projects/blob/main/Copy_of_S9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Stærðfræði og reiknifræði vor 2022, skiladæmi 9**

Nafn: Hjörvar Sigurðsson

Samverkamenn:

# **1. Póker (V34)**

In [ ]:
# Gefið

from random import sample

def pókerhönd():
  stokkur = [(i,j) for i in range(1,5) for j in range(1,14)]
  return sample(stokkur, 5)

def með_tvær_tvennur(hönd):
  # Skilar sönnu ef hönd geymir tvær tvennur
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)                 # búa til mengi
  if len(M) != 3:
    return False                 # það verða að vera 3 gildi
  for spil in M:
    talning = gildi.count(spil)
    if talning > 2: return False # og ekkert spil má koma 3svar
  return True                    # það eru tvær tvennur!

def hlutfall_með_2x2(n):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if með_tvær_tvennur(hönd):
      talning += 1
  return talning/n

hf = hlutfall_með_2x2(100000)
print(f'Hlutfall með tvær tvennur: {hf*100:.1f}%')

Hlutfall með tvær tvennur: 4.7%

In [ ]:
def hlutfall_með_x(n, x):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if x(hönd):
      talning += 1
  return talning/n

In [ ]:
#a

def með_tvennu(hönd):
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)

  for spil in M:
    talning = gildi.count(spil)
    if talning == 2:
      return True
  return False

ha = pókerhönd()
print(ha)
print()
mt = með_tvennu(ha)
print(mt)
print()
hlfmt = hlutfall_með_x(100000, með_tvennu)
print(f'Hlutfall með þrennu: {hlfmt*100:.1f}%. Samkvæmt upplýsingum af netinu er rétt gildi um 42.2569%	.')

[(1, 7), (3, 12), (3, 7), (2, 7), (3, 13)]

False

Hlutfall með þrennu: 47.0%. Samkvæmt upplýsingum af netinu er rétt gildi um 42.2569%	.

In [ ]:
#b

def með_þrennu(hönd):
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)

  for spil in M:
    talning = gildi.count(spil)
    if talning == 3:
      return True
  return False

hb = pókerhönd()
print(hb)
print()
mþ = með_þrennu(hb)
print(mþ)
print()
hlfmþ = hlutfall_með_x(100000, með_þrennu)
print(f'Hlutfall með þrennu: {hlfmþ*100:.1f}%. Samkvæmt upplýsingum af netinu er rétt gildi um 2.1128%.')

[(4, 8), (1, 4), (2, 5), (4, 4), (2, 2)]

False

Hlutfall með þrennu: 2.3%. Samkvæmt upplýsingum af netinu er rétt gildi um 2.1128%.

In [ ]:
#c

def með_fullt_hus(hönd):
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)

  if len(M) != 2:
    return False

  t3 = False
  t2 = False
  for spil in M:
    if gildi.count(spil) == 3:
      t3 = True
    if gildi.count(spil) == 2:
      t2 = True
  if (t3 == True and t2 == True):
    return True
  else: 
    return False

hc = pókerhönd()
print(hc)
print()
mfh = með_fullt_hus(hc)
print(mfh)
print()
hTestc = [(2, 5), (1, 5), (3, 5), (1, 2), (2, 2)]
print(með_fullt_hus(hTestc))
print()
hlfmfh = hlutfall_með_x(100000, með_fullt_hus)
print(f'Hlutfall með fullt hús: {hlfmfh*100:.1f}%. Samkvæmt upplýsingum af netinu er rétt gildi um 0.1441%.')

[(1, 3), (2, 13), (1, 1), (2, 11), (4, 13)]

False

True

Hlutfall með fullt hús: 0.1%. Samkvæmt upplýsingum af netinu er rétt gildi um 0.1441%.

In [ ]:
#d

def með_lit(hönd):
  sort = [spil[0] for spil in hönd]
  M = set(sort)

  cBlack = True
  cRed = True

  for spil in M:
    if (spil == 1 or spil == 3):
      cBlack = False
    if (spil == 2 or spil == 4):
      cRed = False
  
  if (cBlack == True or cRed == True):
    return True
  else:
    return False


hd = pókerhönd()
print(hd)
print()
ml = með_lit(hd)
print(ml)
print()
hTestd = [(2, 1), (2, 2), (2, 3), (4, 1), (4, 2)]
mlt = með_lit(hTestd)
print(mlt)
print()
hlfml = hlutfall_með_x(100000, með_lit)
print(f'Hlutfall með lit: {hlfml*100:.1f}%. Samkvæmt upplýsingum af netinu er rétt gildi um 5%.')

[(1, 12), (4, 1), (4, 3), (4, 9), (4, 12)]

False

True

Hlutfall með lit: 5.0%. Samkvæmt upplýsingum af netinu er rétt gildi um 5%.

# **2. Pandas æfing (V40)**

In [ ]:
import pandas as pd

In [ ]:
#1

df_kosningar = pd.read_fwf('https://cs.hi.is/python/kosningar-2021.txt', index_col=0)
display(df_kosningar)

       Atkvæði  Þingsæti
Listi
B        34501        13
C        16628         5
D        48708        16
F        17672         6
J         8181         0
M        10879         3
O          836         0
P        17233         6
S        19825         6
V        25114         8
Y          144         0

In [ ]:
#2

df_flokksnofn = pd.read_csv('https://cs.hi.is/python/flokksnofn.txt', sep=",\t", index_col=0)
df = df_kosningar.join(df_flokksnofn)
display(df)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

       Atkvæði  Þingsæti              Flokkur
Listi
B        34501        13    Framsóknarflokkur
C        16628         5             Viðreisn
D        48708        16   Sjálfstæðisflokkur
F        17672         6     Flokkur fólksins
J         8181         0    Sósíalistaflokkur
M        10879         3           Miðflokkur
O          836         0  Frjálslyndi lýðrfl.
P        17233         6              Píratar
S        19825         6           Samfylking
V        25114         8         Vinstri græn
Y          144         0        Ábyrg framtíð

In [ ]:
#3

#df["Hlutfall atkvæða"] = df['']

atkvæðiTotal = df['Atkvæði'].sum()
df['Hlutfall atkvæða'] = df['Atkvæði'] / atkvæðiTotal
df3 = df[df['Hlutfall atkvæða'] > 0.05]
display(df3)

       Atkvæði  Þingsæti             Flokkur  Hlutfall atkvæða
Listi
B        34501        13   Framsóknarflokkur          0.172746
C        16628         5            Viðreisn          0.083256
D        48708        16  Sjálfstæðisflokkur          0.243880
F        17672         6    Flokkur fólksins          0.088483
M        10879         3          Miðflokkur          0.054471
P        17233         6             Píratar          0.086285
S        19825         6          Samfylking          0.099263
V        25114         8        Vinstri græn          0.125745